# Branches that trigger a build on commit
trigger:
- master
- release_v*

# Branches that trigger builds on PR
pr:
  branches:
    include:
    - master
    - release_v*
  paths:
    include:
    - cmake/*
    - lib/*
    - pipelines/*
    - resources/*
    - samples/*
    - src/*
    - test/*
    - CMakeLists.txt
    - makeaosp.sh
    - makeios.sh
    - makelinux.sh
    - makemac.sh
    - makewin.cmd
    - manifest.cmakein

jobs:
- job: macOS
  pool:
    name: Hosted macOS
  strategy:
    # TODO: add builds using xerces if needed.
    matrix:
      debug:
        _arguments: -b Debug
        _artifact: MACOSchk
      release:
        _arguments: -b MinSizeRel
        _artifact: MACOS
      release_nobundle:
        _arguments: -b MinSizeRel -sb
        _artifact: MACOS-nobundle
  steps:
  - task: Bash@3
    displayName: Build
    inputs:
      targetType: filePath
      filePath: ./makemac.sh
      arguments: $(_arguments)
      # failOnStderr: true Turn on when https://github.com/Microsoft/azure-pipelines-image-generation/issues/758 is resolved.
    condition: succeeded()

    # Because of the azure pipeline issue we won't fail compiling the code, but 
    # we will fail doing the test because there are no binaries
    # Note: We skip BVTs in Debug mode because of assert()
  - script: 'msixtest/msixtest -s -r junit -o TEST-MsixSDK-$(_artifact).xml'
    workingDirectory: .vs
    displayName: 'macOS BVTs'
    condition: and(succeeded(), contains(variables['Agent.JobName'], 'release'))
  
  - task: PublishTestResults@2
    displayName: 'Publish $(_artifact) Test Results'
    inputs:
      failTaskOnFailedTests: true
      testRunTitle: $(_artifact)
    condition: and(succeeded(), contains(variables['Agent.JobName'], 'release'))

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: .vs
      Contents: |
        bin/makemsix
        bin/makemsix.dSYM/**
        lib/libmsix*
        lib/libmsix*/**
        src/msix/AppxPackaging.hpp
        src/msix/MSIXWindows.hpp
        src/msix/MsixErrors.hpp
        Package.nuspec
        build/**
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    condition: succeeded()

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact $(_artifact)'
    inputs:
      ArtifactName: $(_artifact)
    condition: succeeded()
